### ISSUE TITLE
[Request] Custom Materials

### ISSUE THREAD

**Issue by DSyncd-Cheats** [superyor/BetterChams#3]
Possibly the ability to use custom materials without using GCFScape to find them. like a custom materials folder in the csgo folder where you can put them

**Comment by superyor** [comment]
I can try to implement a custom material option where users can insert their own path.
For example: `"models/inventory_items/trophy_majors/crystal_clear"`

**Comment by superyor** [comment]
Closed because my colleague Cheeseot released AdvancedChams and BetterChams has been discontinued.
